### ISSUE TITLE
Isolate the causes of small numerical discrepancies in vaccination+variant models

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#147]
Issue isolated to the initial state construction, in cases where 100 steps is not sufficient for the eigenvector exponential simulations to converge.  This is good news for the TMB-engine/auto-Jacobian engine, because it implies that the issue was on the R-engine.

**Comment by bbolker** [comment]
surprising that >100 steps needed to converge (are these weird params or a weird structure?), but great to figure it out

**Comment by stevencarlislewalker** [comment]
The example was my (pretty close) approximation to the `macpan_ontario` workflow.  And only somewhere between 140 and 150 steps were required, so at least it is not many more steps.  And even after 100 steps the maximum relative difference between any state variable at any point in time was somewhere between 1e-5 and 1e-6, so again not that bad.  I just wanted to make sure it wasn't a sign of something more sinister.
