### ISSUE TITLE
Ability to turn off objective function computation when forecasting

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#188]
There are two possible approaches:

- Two branches in the C++ code, one for calibration and one for forecasting
- Generate two AD functions, one for calibration and one for forecasting that does not include observed data, priors, or transformations

I like the second one better because it will reduce the complexity of the C++ code and I have found that generating AD functions is quite cheap computationally.

**Comment by stevencarlislewalker** [comment]
Any thoughts @bbolker?

**Comment by bbolker** [comment]
not off the top of my head. Can you do what you want with appropriate use of SIMULATE or analogous macros? (I don't know if !(SIMULATE) works but suspect it would, i.e. wrap objective function computations in if (!SIMULATE) ?

**Comment by stevencarlislewalker** [comment]
Implemented different `flexmodel` classes for different purposes, each of which makes the appropriate links with c++/tmb.
