### ISSUE TITLE
Length-zero date construction fails on Windows  R4.0.0

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#201]
# Steps

1. `library(McMasterPandemic)`
2. `flexmodel(params = c(a = 1), state = c(b = 1))`

# Actual Result

```
 Error in as.Date.numeric(numeric(0L)) : 'origin' must be supplied
```

# Expected Results

```
data frame with 0 columns and 0 rows
```

**Comment by stevencarlislewalker** [comment]
Caused by initializing zero-length date vectors, in a manner that is either R version-dependent or OS-dependent.

A possible solution is to use `structure(..., class = "Date")` instead of `as.Date`, but this seems hacky.

**Comment by Flynn-Primrose** [comment]
Changed `as.Date.numeric(numeric(0L))` to `as.Date.numeric(numeric(0L), origin = "1970-01-01")`
