### ISSUE TITLE
shiny app link not found

### ISSUE THREAD

**Issue by carolinecolijn** [mac-theobio/McMasterPandemic#241]
The readme page points to this link for the shiny app https://mcmasterpandemic.shinyapps.io/mcmasterpandemicshiny/ and chrome says the link can't be found

**Comment by stevencarlislewalker** [comment]
Thanks @carolinecolijn.  This link needs to be removed -- I'll do that.  The app is very old and out of date.  Goes back to before I started.

Also, we have moved over [here](https://github.com/canmod/macpan2) for new development.  I need to add this to the readme as well.

**Comment by davidearn** [comment]
Caroline, go to https://github.com/canmod/macpan2

The original McMasterPandemic has been replaced by macpan2.

I'll ask Steve to make this clear on this page. The shiny app was 
associated with the original version and has not been updated for a very 
long time.  We'll clean that up as well.

Thanks,

David

**Comment by stevencarlislewalker** [comment]
Fixed with 78568775f95e3e889c1d5e01602b0596431e16b8
