### ISSUE TITLE
forecast CIs based on sampled parameter value instead of on MLE

### ISSUE THREAD

**Issue by papsti** [mac-theobio/McMasterPandemic#54]
When we produce forecasts based on increases to the transmission rate, we want to take the last fitted relative beta0 and scale it up by, *e.g.*, 30%. One idea would be to add a line to `model$fit$forecast_args$time_args$params_timevar` setting a new relative beta0 on the first forecast date as `1.3*last_fitted_rel_beta0` before calling `forecast_ensemble()`. However, for each realization in `forecast_ensemble()`, we're sampling new relative beta0s from a multivariate normal parameterized by the MLEs and the covariance matrix in order to generate CIs on the MLE. This works well in the fit period, but in the forecast period, we'd have to update the forecast transmission rate by scaling the sampled last fitted relative beta0. How do we implement this in a smart way so that the forecast CIs actually use the parameter sampling for each realization?

**Comment by bbolker** [comment]
This is done with the `flex_timevars` branch merge.
