### ISSUE TITLE
Various problems with examples introduced by ip_devel merge

### ISSUE THREAD

**Issue by matthewcso** [mac-theobio/McMasterPandemic#58]
Currently done: Added make_betavec back, fixed problems with compiling vignettes

- `vis_model(method="diagram")` is broken, switched to `igraph` for now ` Error in .local(x, i, j, ..., value) : 
  not-yet-implemented 'Matrix[<-' method `
- make_ratemat breaks with this error ` Error in .local(x, i, j, ..., value) : 
  not-yet-implemented 'Matrix[<-' method `
- rExp: `Error in if (return_val == "r0" && var(r0_values) > 1e-08) warning("the exponential simulation has not converged: please iterate for more steps.") : 
  missing value where TRUE/FALSE needed`
- vis_model: ` Error in .local(x, i, j, ..., value) : 
  not-yet-implemented 'Matrix[<-' method `

`Additional R CMD Check Warnings
Warning messages:
1: In tools::parse_Rd(path, macros = macros) :
  C:/Users/somat/Documents/GitHub/McMasterPandemic/man/expand_params_variant.Rd:22: unknown macro '\item'
2: In tools::parse_Rd(path, macros = macros) :
  C:/Users/somat/Documents/GitHub/McMasterPandemic/man/expand_params_variant.Rd:24: unknown macro '\item'
3: In tools::parse_Rd(path, macros = macros) :
  C:/Users/somat/Documents/GitHub/McMasterPandemic/man/expand_params_variant.Rd:26: unexpected section header '\description'
4: In tools::parse_Rd(path, macros = macros) :
  C:/Users/somat/Documents/GitHub/McMasterPandemic/man/expand_params_variant.Rd:29: unexpected section header '\examples'
5: In tools::parse_Rd(path, macros = macros) :
  C:/Users/somat/Documents/GitHub/McMasterPandemic/man/expand_params_variant.Rd:33: unexpected END_OF_INPUT '`

**Comment by bbolker** [comment]
The unknown macro/unexpected END_OF_INPUT stuff was caused by an unescaped `%` in the documentation, that's fixed now.

**Comment by bbolker** [comment]
`vis_model` and `make_ratemat` stuff should be fixed now.

**Comment by bbolker** [comment]
`rExp` example is fixed (sort of, although `rExp` should probably still be examined: see also #51 ). There is still an error with`tests/test_calibrate.R` (**not** tested via `devtools::test()`) and a bunch of undocumented arguments and undefined symbols (unimported or used via non-standard evaluations)

**Comment by bbolker** [comment]
@matthewcso , I guess you're working on this; let me know if I can help

**Comment by matthewcso** [comment]
@bbolker You solved all the bullet points in this issue (examples breaking), so I'll close this and open a new issue for the other rcmdcheck issues.
