### ISSUE TITLE
rescue pkgdown stuff

### ISSUE THREAD

**Issue by bbolker** [mac-theobio/McMasterPandemic#60]
Matt's pkgdown stuff  appears to have been trashed by the ip_devel merge.  I am comparing the two commits circled in red in the accompanying picture ...

![badmerge](https://user-images.githubusercontent.com/78918/122857665-d56e0380-d2e6-11eb-96d0-f40a559b4c35.png)

```
git checkout f1e62cc4f0963
## "benchmark pass-by-value and pass-by-reference [skip ci] "
## right BEFORE ip_devel merge
grep pkgdown * 2> /dev/null


Makefile:       echo "pkgdown.extras::build_site(lazy=TRUE)" | $(R) --slave
Makefile:       echo "pkgdown.extras::build_site()" | $(R) --slave
README.md:See the accompanying [pkgdown
site](https://bbolker.github.io/McMasterPandemic).
README.md:* re-build the `pkgdown.extras` site by using Actions -->
pkgdown --> (This workflow has a workflow_dispatch event trigger.) Run
workflow. Will try to fix this to run on push in the near future.


git checkout 3389eaa4   
## "merge branch 'ip_devel'"
grep pkgdown * 2> /dev/null

<crickets>
```

   Hopefully someone other than me can figure out what happened and fix
it tomorrow ...

**Comment by bbolker** [comment]
I see that @matthewcso added some stuff back in 7751a1cca3, but at present https://mac-theobio.github.io/McMasterPandemic/ is still giving a 404.  Any ideas?

**Comment by matthewcso** [comment]
I rescued the GH Action for pkgdown, but now it just fails completely. I'm working on fixing a million devtools::check() problems related to the merge, hopefully  the problem will be easier to resolve once these things are done.

**Comment by matthewcso** [comment]
The pkgdown workflow failed because the merge removed the docs folder (therefore converting all the docs contents into untracked files). I fixed this issue, we shouldn't have to worry about the pkgdown workflow anymore.

https://mac-theobio.github.io/McMasterPandemic/
