### ISSUE TITLE
Reduce the length of a lot of file names (potentially ignorable? It's just a note...)

### ISSUE THREAD

**Issue by matthewcso** [mac-theobio/McMasterPandemic#61]
R CMD CHECK doesn't want file names longer than 100 bytes. This causes a problem with the following file paths:

N  checking for portable file names ... 
   Found the following non-portable file paths:
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_British_Columbia_F_community_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_British_Columbia_F_household_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_British_Columbia_F_school_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_British_Columbia_M_overall_contact_matrix_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_British_Columbia_age_distribution_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Manitoba_M_overall_contact_matrix_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_New_Brunswick_F_community_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_New_Brunswick_F_household_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_New_Brunswick_M_overall_contact_matrix_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Newfoundland_and_Labrador_F_community_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Newfoundland_and_Labrador_F_household_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Newfoundland_and_Labrador_F_school_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Newfoundland_and_Labrador_F_work_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Newfoundland_and_Labrador_M_overall_contact_matrix_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Newfoundland_and_Labrador_age_distribution_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Northwest_Territories_F_community_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Northwest_Territories_F_household_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Northwest_Territories_F_school_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Northwest_Territories_F_work_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Northwest_Territories_M_overall_contact_matrix_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Northwest_Territories_age_distribution_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Nova_Scotia_M_overall_contact_matrix_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Prince_Edward_Island_F_community_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Prince_Edward_Island_F_household_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Prince_Edward_Island_F_school_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Prince_Edward_Island_F_work_setting_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Prince_Edward_Island_M_overall_contact_matrix_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Prince_Edward_Island_age_distribution_85.csv
     McMasterPandemic/inst/params/mistry-cmats/Canada_subnational_Saskatchewan_M_overall_contact_matrix_85.csv
   
   Tarballs are only required to store paths of up to 100 bytes and cannot
   store those of more than 256 bytes, with restrictions including to 100
   bytes for the final component.
   See section 'Package structure' in the 'Writing R Extensions' manual.

**Comment by bbolker** [comment]
We should indeed fix this if possible.
