### ISSUE TITLE
Fix Roxygen documentation

### ISSUE THREAD

**Issue by matthewcso** [mac-theobio/McMasterPandemic#63]
N  checking Rd files (874ms)
   prepare_Rd: aggregate_agecats.Rd:16-18: Dropping empty section \value
   prepare_Rd: expand_params_desc_age.Rd:13-15: Dropping empty section \value
   prepare_Rd: expand_params_desc_variant.Rd:13-15: Dropping empty section \value
   prepare_Rd: expand_params_desc_vax.Rd:15-17: Dropping empty section \value
   prepare_Rd: plot_res_by_age.Rd:16-18: Dropping empty section \value
   prepare_Rd: plot_res_by_state.Rd:21-23: Dropping empty section \value
   prepare_Rd: prep_res_for_plotting.Rd:21-23: Dropping empty section \value
   prepare_Rd: update_params_mistry.Rd:20-22: Dropping empty section \value

W  checking Rd \usage sections (565ms)
   Undocumented arguments in documentation object 'check_contact_rate_setting'
     'contact_rate_setting'
   
   Undocumented arguments in documentation object 'expand_params_mistry'
     'params'
   
   Undocumented arguments in documentation object 'forecast_ensemble'
     'parallel' 'n_cores'
   
   Undocumented arguments in documentation object 'get_doses_per_day'
     'dose'
   
   Undocumented arguments in documentation object 'make_state'
     'ageify' 'vaxify'
   
   Undocumented arguments in documentation object 'plot_res_by_age'
     'condense_I'
   
   Undocumented arguments in documentation object 'plot_res_by_state'
     'condense_I'
   
   Undocumented arguments in documentation object 'prep_res_for_plotting'
     'condense_I'
   
   Undocumented arguments in documentation object 'rExp'
     'state'
   
   Undocumented arguments in documentation object 'show_ratemat'
     'xlab' 'ylab' 'sub' 'zlim'
   
   Functions with \usage entries need to have the appropriate \alias
   entries, and all their arguments documented.
   The \usage entries must correspond to syntactically valid R code.
   See chapter 'Writing R documentation files' in the 'Writing R
   Extensions' manual.

**Comment by matthewcso** [comment]
The above notes were caused by having a `@return` without an `@return` description. I have made reasonable guesses for all of the Rd \usage issues, please double-check the descriptions for "condense_I" (plot_res_by_age and others) and "dose" (get_doses_per_day). Note that the parameter `zlim` appears to be unused in show_ratemat.

**Comment by bbolker** [comment]
Have you pushed? Can't find these changes on the repo ...

**Comment by matthewcso** [comment]
I forgot to push. The issues should be fixed by the commit  `478e520bf20279a2bd803da1301fc3cb15f03a34`.
