### ISSUE TITLE
Set up development environment for TMB refactoring project

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#70]
- [x] Decide how to build development environment -- options seem to be Local Windows machine, Sharcnet CentOS server, Linux emulation of some kind (VMs, Docker, something else?)
- [x] Install system dependencies
- [x] Successfully run `make dependencies`
- [x] Successfully run `make build-package`
- [x] Successfully run `make doc-update`
- [x] Successfully run `make install`
- [x] Successfully run `make pkgcheck`
- [x] Successfully run `make pkgtest`
- [x] Successfully run `make style`
- [x] Start R and load McMasterPandemic using `library(McMasterPandemic)` successfully
- [x] Get the Getting Started PDF with `vignette("getting_started", package="McMasterPandemic")`

**Comment by guanwg** [comment]
I've tried first on our cluster (graham). It has some issues (which could be solved, but I don't waste more time). I'm now building the dev environment on WSL/ubuntu. I also requested a VM yesterday which may take up to 48 hours to be approved.

**Comment by stevencarlislewalker** [comment]
Thanks for the update @guanwg.

**Comment by stevencarlislewalker** [comment]
FYI @bbolker and @davidearn, @guanwg has finished setting up his development environment.
