### ISSUE TITLE
Add a `TMB_do_step` function to the package

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#74]
- [x] Have an R/C++ script that matches at least one test case of do_step (e.g. https://github.com/mac-theobio/McMasterPandemic/blob/tmb/notes/example.R matches https://github.com/mac-theobio/McMasterPandemic/blob/tmb/notes/exampleTMB.R)
- [ ] Roxygen documentation for `TMB_do_step` that references `do_step` and clarifies the differences
- [x] Include required C++ files/setup so that `R CMD install` will export `TMB_do_step` to users

**Comment by guanwg** [comment]
This is exactly what I'm going to do in the coming week.

**Comment by guanwg** [comment]
Steve, can tell me how to do the two "checkbox" tasks or point me to some links of related topics?

**Comment by stevencarlislewalker** [comment]
https://stackoverflow.com/questions/48627069/guidelines-for-including-tmb-c-code-in-an-r-package

**Comment by stevencarlislewalker** [comment]
I'm starting to think that this is out-dated and is superseded by #87.  TODO: consider closing this.

**Comment by stevencarlislewalker** [comment]
Superseded by #87, which is also done
