### ISSUE TITLE
Getting Started Vignette is 118 Pages

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#75]
Steps:
1. Build getting started vignette
2. Open it

Actual Result:  the PDF is 118 pages with one line per page for the `calibrateTOres1obs` chunk

Expected Result:  the `calibrateTOres1obs` chunk is rendered without all those line breaks

Commit at time of reporting:  0cfcb61

Environments:
* MacOS Big Sur using `make dependencies`
* Pkgdown GitHub action -- result here https://mac-theobio.github.io/McMasterPandemic/articles/getting_started.html

**Comment by stevencarlislewalker** [comment]
Discovered by @guanwg

**Comment by davidearn** [comment]
I have encountered this many times over the years.  The last time I 
compiled the vignette I got the same behaviour, but - ahem - after edits 
someone else had made :)  Anyway, my previous suspicion has been that this 
is associated with a bug in knitr that runs into trouble when certain 
types of code chunks spill over to another page.  Perhaps just with chunks 
that are more than one full page in length.  Not sure.

David

**Comment by bbolker** [comment]
@davidearn, can you point to a commit that caused this problem? If so, we could probably narrow down the cause/find a way to work around it.

**Comment by stevencarlislewalker** [comment]
Thanks @davidearn.  Adding `\newpage` does not help, but maybe because it still wouldn't fit on a single page.  There is some weird (in my opinion) piping style, with pipes nested within an argument list.

**Comment by bbolker** [comment]
(1) I don't see the weird piping you're referring to?; (2) there are **lots** of warnings. We should probably try to revise this section and/or the code to deal with them. It's OK to have a few warnings and include them to let the user know they are harmless, but what's there looks like a mess.  Suppressing warnings in some places, and breaking longer code chunks into shorter ones, helped both with diagnostics and with cleanup ...

**Comment by stevencarlislewalker** [comment]
Yes you are right @bbolker  ... I mistook this:
```
report_data <- (res1proc2
    %>% mutate(value=round(report), var="report")
    %>% select(date, value, var)
    %>% na.omit()
)
```
For pipes nested within arguments.

Thanks for the details.

**Comment by bbolker** [comment]
That is admittedly a non-standard format, but JD likes it (and I agree) because it means that the pipe can be at the beginning of each line rather than the end,  which makes it easier to comment out individual lines (including the last line) for debugging/exploration purposes.

**Comment by davidearn** [comment]
I've adopted that style too, for the same reason.
D

**Comment by bbolker** [comment]
We have been doing that sporadically.  Might as well.

**Comment by stevencarlislewalker** [comment]
I only want to do it if it really means something.  For example, if you were just going to fix this I would stop working on it so that I don't waste time.

**Comment by stevencarlislewalker** [comment]
I recommend the following:
1. Suppress all warnings for the getting started vignette so that we fix this immediate issue
2. Remove or reword @davidearn's comment https://github.com/mac-theobio/McMasterPandemic/blob/0cfcb61ea8f91a9b61e0ad2cd0f004b4742a2de2/vignettes/getting_started.Rnw#L314
3. Create a new issue to clean up warnings in the package itself, and then bring these useful warnings back to the vignette once/if this new issue is resolved

Any objections @bbolker or others?
