### ISSUE TITLE
Merge/rebase master back into the tmb branch before we get too far out-of-sync

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#76]
- [x] Read https://superuser.com/questions/224085/git-merge-master-into-a-branch
- [x] Bring master and TMB back in sync

**Comment by guanwg** [comment]
used "git rebase master" command.

**Comment by stevencarlislewalker** [comment]
Thank you!

**Comment by stevencarlislewalker** [comment]
Although I'm a little confused.  I expected to see TMB ahead of Master, and Master unchanged.  But it looks like TMB has also not changed:
![image](https://user-images.githubusercontent.com/2754158/128203310-a6a82852-aa6c-4cd6-976d-2ef8567c739d.png)

**Comment by bbolker** [comment]
Looks like `tmb` got merged into `tmb` ? (This is from Insights/ Network)

![Screenshot from 2021-08-04 11-03-28](https://user-images.githubusercontent.com/78918/128205041-07c6071a-2e7a-449f-a0cc-5dc4ddece493.png)

**Comment by stevencarlislewalker** [comment]
Thanks @bbolker.
@guanwg, let's leave it as is for now. I was planning on doing this myself anyways, but didn't consider it priority right now.

**Comment by guanwg** [comment]
I thought you asked me to do it. Sorry! I need to get familiar with github project management. 
The latest commit to tmb is made 4 days ago. https://github.com/mac-theobio/McMasterPandemic/commit/44dfa0438aa4f48f0a334eb54dc47854bea807de

**Comment by stevencarlislewalker** [comment]
Not a problem. I didn't point out the assignee field.

**Comment by stevencarlislewalker** [comment]
Used a merge instead of rebase, because [this](https://superuser.com/questions/224085/git-merge-master-into-a-branch) says that merges are safer when you are collaborating _with others_ on feature branches.
