### ISSUE TITLE
Test TMB gradient

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#88]
For @guanwg
- [x] Write TMB code to return the sum of the state variables at the final iteration, as the mock objective function

For @stevencarlislewalker
- [x] Choose mock objective function -- sum of state variables at the final iteration
- [x] Test on spec version 0.0.5
- [x] Write numDeriv-based script for computing the derivative of the chosen state
- [x] Compare numeric and TMB based derivatives using all.equal relative tolerance

**Comment by guanwg** [comment]
Have returned sum of state vector at the final iteration in the latest checked-in (inst/tmb/0.0.5/macpan.cpp)

**Comment by stevencarlislewalker** [comment]
See https://github.com/mac-theobio/McMasterPandemic/commit/53ff89e8e31372016359c0374121d6456b20e148
