### ISSUE TITLE
More gracefully handle printouts from cpp files in the tmb test harness located at `inst/tmb`

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#95]
As someone who inspects test logs, I want the default behaviour to show details for test failures only, so that I don't get distracted by unimportant information.

Currently there are cpp files in `inst/tmb` that give too many details. One solution would be to remove these, but perhaps it would be better to configure the `testthat` functionality so that these printouts are only shown on test failures -- but not sure if this is possible.

**Comment by bbolker** [comment]
There is a standard way to handle this; if you set

```
CXXFLAGS+=-Wno-ignored-attributes 
CXX11FLAGS+=-Wno-ignored-attributes
CXX14FLAGS+=-Wno-ignored-attributes
```
in your `~/.R/Makevars` file, it will suppress most (maybe not all?) of the build warnings.

This behaviour is explicitly *disallowed* by the CRAN maintainers (long story), so it will provoke a WARNING when you run `R CMD check`.

Does that help? (Not sure ...)

**Comment by stevencarlislewalker** [comment]
Thanks @bbolker!  I'm not sure if it helps yet, but it will be a great place to start when I get to this.

**Comment by guanwg** [comment]
Regarding " Currently there are cpp files in inst/tmb that give too many
details.", I actually use quite a few std::cout << ... to print values of
variables for debug purposes only. I can easily remove them.

Weiguang

**Comment by bbolker** [comment]
You should give some thought to whether you want to remove them or whether you want to set a debugging flag (either as an `#ifdef`, or if you're being fancy, you can add a binary debugging flag to the DATA specification ...)

**Comment by stevencarlislewalker** [comment]
I agree with Ben.  We should add a debug flag to the DATA spec.

**Comment by guanwg** [comment]
Do you mean by " the DATA spec" https://canmod.net/misc/flex_specs?

Weiguang

**Comment by stevencarlislewalker** [comment]
No ... I'm sorry, I thought that that might be confusing.  I mean the `DATA` macro in the `TMB` `C++` framework.

**Comment by stevencarlislewalker** [comment]
Close due to https://github.com/mac-theobio/McMasterPandemic/commit/680737da4a24e687fa4b041b41521467077645f8.  Going to not bother with a `verbose` or `debug` flag for now.
